### ISSUE TITLE
LinkSyntax interfering with other custom inline syntax

### ISSUE THREAD

**Issue by vHanda** [dart-lang/markdown#293]
Hello

```dart
import 'package:markdown/markdown.dart' as md;

void main() {
  var body = "[[GitJournal]] should match.\n- [ ] task item";
  var lines = body.split('\n');

  var doc = md.Document(
    encodeHtml: false,
    extensionSet: md.ExtensionSet.gitHubFlavored,
    inlineSyntaxes: [WikiLinkSyntax(), TaskListSyntax()],
  );
  doc.parseLines(lines);
  // Prints -
  // -------- WIKI LINK -------

  doc = md.Document(
    encodeHtml: false,
    extensionSet: md.ExtensionSet.gitHubFlavored,
    inlineSyntaxes: [TaskListSyntax(), WikiLinkSyntax()],
  );
  doc.parseLines(lines);

  // Prints -
  // -------- TASK LIST -------"
}

// Match `[[word]]`
class WikiLinkSyntax extends md.InlineSyntax {
  static final String _pattern = r'\[\[([^\[\]]+)\]\]';

  WikiLinkSyntax() : super(_pattern);

  @override
  bool onMatch(md.InlineParser parser, Match match) {
    print("-------- WIKI LINK -------");
    return true;
  }
}

// Match `[ ] item`
class TaskListSyntax extends md.InlineSyntax {
  static final String _pattern = r'^ *\[([ xX])\] +';

  TaskListSyntax() : super(_pattern);

  @override
  bool onMatch(md.InlineParser parser, Match match) {
    print("-------- TASK LIST -------");
    return true;
  }
}

```

Depending on the order of the `inlineSyntaxes`, one of the parsers is ignored. Debugging this more, it seems it is related to - https://github.com/dart-lang/markdown/blob/master/lib/src/inline_parser.dart#L92 where the order of the `inlineSyntaxes` cannot be controlled externally and the `LinkParser` always runs after the first parser.

Changing -
```
syntaxes.insertAll(1, [
      LinkSyntax(linkResolver: document.linkResolver),
      ImageSyntax(linkResolver: document.imageLinkResolver)
    ]);
```
to
```
syntaxes.insertAll(2, [
      LinkSyntax(linkResolver: document.linkResolver),
      ImageSyntax(linkResolver: document.imageLinkResolver)
    ]);
```

fixes the issue. But this is a horrible fix.

The real problem is that the LinkParser interferes with the other parsers even though the markdown in question has no links.

**Comment by srawlins** [comment]
Good catch. LinkSyntax is added twice, but only the second is needed. If Document.linkResolver is null, then LinkSyntax will use a default resolver.

**Comment by srawlins** [comment]
Fixed with #295

**Comment by vHanda** [comment]
Would it be possible to make a new release, please?

This way I don't need to maintain my fork :)

**Comment by srawlins** [comment]
Thanks for the ping; bumping version in #297

**Comment by vHanda** [comment]
I just tried this out, and it seems that this still occurs with the latest version. Could this bug please be re-opened?

I've created a test which we could add to this repo? Should i make a pull request?

https://github.com/GitJournal/GitJournal/blob/master/test/markdown_bug_test.dart

**Comment by srawlins** [comment]
Thanks, yes please file a pull request. That would be very helpful to find why it was not fixed for you.

**Comment by vHanda** [comment]
This seems to be fixed in the latest version. Closing.
